Repository SchwarzIT/node-red-chart, pull requests merged in 2022-01, with the labels that each got.

#28 Added init container to fix permissions
  charts/node-red/Chart.yaml
  charts/node-red/templates/deployment.yaml
Labels: size/S

#30 feat: add ossf-scorecard-action
  .github/workflows/lint-and-test.yml
  .github/workflows/ossf-scorecard-action.yaml
  .github/workflows/publish.yaml
Labels: size/L

#35 feat: rework chart readme generation
  .github/workflows/ossf-scorecard-action.yaml
  .github/workflows/publish.yaml
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/README.md.gotmpl
  charts/node-red/values.yaml
Labels: size/L

#36 Readme
  .github/workflows/ossf-scorecard-action.yaml
  .github/workflows/publish.yaml
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/README.md.gotmpl
  charts/node-red/values.yaml
Labels: size/L

#41 feat: fix actions with renovate annotation
  .github/workflows/lint-and-test.yml
  .github/workflows/ossf-scorecard-action.yaml
  .github/workflows/publish.yaml
Labels: size/M
