Repository SchwarzIT/node-red-chart, pull requests merged in 2022-02, with the labels that each got.

#46 docs: add SECURITY file
  SECURITY.md
Labels: size/M

#47 feat: add issue forms and Artifact lint
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature.yaml
  .github/workflows/lint-and-test.yml
  .github/workflows/publish.yaml
  CODE_OF_CONDUCT.md
Labels: size/L

#53 chore: trigger release
  charts/node-red/Chart.yaml
Labels: size/XS

#55 chore: update app version
  charts/node-red/Chart.yaml
  charts/node-red/README.md
Labels: size/S

#56 feat: adding support for cert-manager certificates
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/README.md.gotmpl
  charts/node-red/templates/_helpers.tpl
  charts/node-red/templates/certificates.yaml
  charts/node-red/values.yaml
Labels: size/M

#58 feat: add extra volume support
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/templates/deployment.yaml
  charts/node-red/values.yaml
Labels: size/M

#59 feat: add custom node-red container image
  .github/workflows/ci.yaml
  Dockerfiles/Dockerfile
  Dockerfiles/Makefile
Labels: size/L

#60 feat: add write permission to pipeline
  .github/workflows/build-docker-images.yaml
Labels: size/XS

#61 fix: remove permission on release job
  .github/workflows/build-docker-images.yaml
Labels: size/XS

#62 Passport oauth2
  Dockerfiles/Dockerfile
Labels: size/XS

#63 feat: adding npm nodes
  Dockerfiles/Dockerfile
Labels: size/XS

#65 Version230
  Dockerfiles/Dockerfile
  charts/node-red/Chart.yaml
  charts/node-red/README.md
Labels: size/S

#69 feat: fix makefile version
  Dockerfiles/Dockerfile
  Dockerfiles/Makefile
Labels: size/XS

#72 fix: remove broken chart 0.8.0
  charts/node-red/Chart.yaml
  charts/node-red/README.md
Labels: size/S
