Repository SchwarzIT/node-red-chart, pull requests merged in 2022-03, with the labels that each got.

#73 feat: rework build pipeline for custom container image
  .github/workflows/build-docker-images.yaml
  Dockerfiles/Dockerfile
  Dockerfiles/Makefile
Labels: size/M

#74 fix: add version to push in Makefile
  Dockerfiles/Makefile
Labels: size/XS

#80 feat: adding optional value initContainers
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/templates/deployment.yaml
  charts/node-red/values.yaml
Labels: size/S

#81 fix: indent of initContainers
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/templates/deployment.yaml
Labels: size/M

#85 feat: add support for sidecars
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/templates/deployment.yaml
  charts/node-red/values.yaml
Labels: size/L

#86 feat: remove custom node-red image container build
  .github/workflows/build-docker-images.yaml
  Dockerfiles/Dockerfile
  Dockerfiles/Makefile
Labels: size/M

#88 feat: adding optional Prometheus support
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/README.md.gotmpl
  charts/node-red/templates/deployment.yaml
  charts/node-red/templates/servicemonitor.yaml
  charts/node-red/templates/tests/test-connection.yaml
  charts/node-red/values.yaml
Labels: size/L

#89 feat: add optional prometheus support for node-red
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/templates/deployment.yaml
Labels: size/S

#90 fix: change port name of servicemonitor to default port
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/templates/servicemonitor.yaml
Labels: size/S

#91 fix: add annotation support for deployment manifest
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/templates/deployment.yaml
  charts/node-red/values.yaml
Labels: size/S
