Repository SchwarzIT/node-red-chart, pull requests merged in 2022-04, with the labels that each got.

#95 feat: add sidecar for flow reload
  .github/workflows/lint-and-test.yml
  charts/node-red/.helmignore
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/README.md.gotmpl
  charts/node-red/scripts/flow_refresh.sh
  charts/node-red/templates/deployment.yaml
  charts/node-red/templates/sidecar-cm.yaml
  charts/node-red/tests/deployment_test.yaml
  charts/node-red/tests/flow_refresh_cm_test.yaml
  charts/node-red/tests/values/sidecar_values.yaml
  charts/node-red/values.yaml
Labels: size/L

#97 fix: fix defaultMode on refresh script
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/templates/deployment.yaml
  charts/node-red/tests/deployment_test.yaml
  charts/node-red/tests/values/sidecar_values.yaml
  charts/node-red/values.yaml
Labels: size/S

#98 fix: if condition on volume
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/templates/deployment.yaml
Labels: size/XS

#100 fix: add slash to folder value
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/templates/deployment.yaml
  charts/node-red/tests/deployment_test.yaml
Labels: size/S

#101 Fix4
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/scripts/flow_refresh.sh
  charts/node-red/templates/deployment.yaml
  charts/node-red/tests/deployment_test.yaml
Labels: size/S

#107 fix: remove initContainer and work with runAsUser and fsGroup
  charts/node-red/Chart.yaml
  charts/node-red/templates/deployment.yaml
  charts/node-red/values.yaml
Labels: size/S

#109 fix: basic-auth support for servicemonitor
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/values.yaml
Labels: size/S

#111 fix: sidecar ConfigMapName
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/templates/_helpers.tpl
  charts/node-red/templates/deployment.yaml
  charts/node-red/templates/sidecar-cm.yaml
  charts/node-red/tests/flow_refresh_cm_test.yaml
Labels: size/S
