Repository SchwarzIT/node-red-chart, pull requests merged in 2022-08, with the labels that each got.

#138 chore: update node-red to 3.0.2
  charts/node-red/Chart.yaml
  charts/node-red/README.md
Labels: size/S

#140 feat: add Trivy suggestions to helm chart values
  charts/node-red/Chart.yaml
  charts/node-red/README.md
  charts/node-red/values.yaml
Labels: size/M

#141 feat: add trivy support
  .github/workflows/lint-and-test.yml
Labels: size/S

#142 chore: pin version of github/codeql-action/upload-sarif
  .github/workflows/lint-and-test.yml
Labels: size/XS
