Repository SchwarzIT/node-red-chart, pull requests merged in 2024-09, with the labels that each got.

#344 fix: Incorrect chart values for user, group and memory limit
  charts/node-red/Chart.yaml
  charts/node-red/values.yaml
Labels: size/XS, waiting-for-feedback

#346 4.0.3
  charts/node-red/Chart.yaml
  charts/node-red/README.md
Labels: size/S

#347 Update README.md
  README.md
Labels: size/XS
