Repository SchwarzIT/node-red-chart, pull requests merged in 2025-06, with the labels that each got.

#423 feat: add dependabot support and check quality
  .github/dependabot.yml
Labels: size/S

#425 fix: helm-docs
  .github/workflows/publish.yaml
  .github/workflows/update-docs.yaml
Labels: size/M

#406 Update Node-RED to version 4.0.9
  charts/node-red/Chart.yaml
Labels: size/XS

#427 fix: helm-docs
  .github/workflows/update-docs.yaml
Labels: size/XS

#429 Helm docs
  .github/workflows/update-docs.yaml
Labels: size/XS
